name: Trigger Tests
on:
  push:
    branches: [ "main", "actions/**" ]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: | 
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "The current branch name is $BRANCH_NAME"
      - name: "[Database] Check if current branch exists"
        id: check_branch_db
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/DevOps-2023-TeamA/tsao-db/branches/branch_name")
          if [ "$BRANCH_EXISTS" -eq 200 ]; then
            echo "[Database] Branch exists."
            echo "::set-output name=branch::branch_name"
          else
            echo "[Database] Branch does not exist. Using main."
            echo "::set-output name=branch::main"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "[Database] Trigger Database Tests on the specified branch"
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/DevOps-2023-TeamA/tsao-db/actions/workflows/tests.yml/dispatches \
          -d '{"ref":"${{ steps.check_branch_db.outputs.branch }}"}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "[Database] Check if current branch exists"
        id: check_branch_fe
        run: |
          BRANCH_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/DevOps-2023-TeamA/tsao-frontend-svc/branches/branch_name")
          if [ "$BRANCH_EXISTS" -eq 200 ]; then
            echo "[Database] Branch exists."
            echo "::set-output name=branch::branch_name"
          else
            echo "[Database] Branch does not exist. Using main."
            echo "::set-output name=branch::main"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "[Frontend] Trigger Frontend Tests on the specified branch"
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/DevOps-2023-TeamA/tsao-frontend-svc/actions/workflows/tests.yml/dispatches \
          -d '{"ref":"${{ steps.check_branch_fe.outputs.branch }}"}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
